name: Build

on:
  push:
  workflow_dispatch:

jobs:
  inclination_idl_fastdds:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        platform: [ubuntu-24.04] #, ubuntu-22.04-arm] #, ubuntu-24.04-arm]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set-up dependancies
      run: |
        codename=$(lsb_release -c -s)
        echo "deb [trusted=yes] https://alest-software.github.io/ubuntu ${codename} main" | sudo tee /etc/apt/sources.list.d/alest-software.list
        sudo apt update
        sudo apt install -y cmake g++ python3-pip wget git
        sudo apt install -y libasio-dev libtinyxml2-dev
        sudo apt install -y libssl-dev
        sudo apt install -y libp11-dev
        sudo apt install -y softhsm2
        sudo apt install -y libengine-pkcs11-openssl
        sudo apt install -y libfoonathan-memory-dev
        sudo apt install -y libfastcdr libfastdds libfastdds-python fastddsgen

    - name: Build
      run: |
        make --file=./build.mk all
        
    - name: Deploy
      run: |
        codename=$(lsb_release -c -s)
        git clone --depth 1 https://x-access-token:${{ secrets.TOKEN }}@github.com/alest-software/ubuntu.git
        for fn in ./*.deb; do
          arch=$(dpkg --info ${fn} | awk '/Architecture:/ {print $2}')
          fname=$(basename ${fn})
          dest="dists/$codename/main/binary-$arch"
          mkdir -p "ubuntu/${dest}"
          cp "${fn}" "ubuntu/${dest}/${fname}"
          (cd ubuntu; git add "${dest}/${fname}")
        done
        cd ubuntu
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git commit -m 'Automatic deployment' || echo 'Nothing to commit'
        git push
